name: PR Title Check
on:
  pull_request:
    types: [ opened, edited ]
permissions:
  pull-requests: write
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read allowed keywords and rules from YAML
        id: read-keywords
        uses: mikefarah/yq@v4
        with:
          cmd: yq '.allowed_keywords' infra/config/validation.yaml -o=json
      - name: Validate PR title
        id: validate
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          ALLOWED_KEYWORDS_JSON: ${{ steps.read-keywords.outputs.stdout }}
        run: |
          echo "Validating PR title: '$PR_TITLE'"
          
          # Check if the child script reported an error
          if ! source infra/scripts/conventional-titles/parse-title.sh "$PR_TITLE"; then
            gh pr comment ${{ github.event.pull_request.number }} --body "> [!WARNING]
            > PR title validation failed!
            $MESSAGES"
            exit 1
          else
            gh pr comment ${{ github.event.pull_request.number }} --body "> [!NOTE]
            > PR title validation succeeded.
            $MESSAGES"
          fi
